### PR TITLE
Adjust Dog Whistle to allow custom tags per-message

### PR DESCRIPTION
**Pull request by jeremyist**
This PR includes the ability to allow custom tags per-message. This can be turned on/off via the `allow_extra_tags` configuration  boolean.  An example message with custom tags is below:

```
logger.info("this is a test",extra={'tags': ['my:tag', 'my:othertag']})
```

I have also updated the docs and made a note about tags not working on a `local=True` setup.

### CODE REVIEW

**Comment by madisonb** [comment]
Can you add a small unit test to cover the expected behavior for when the flag is set to `True`?

**Comment by joequery** [comment]
When extra tags are provided, they should be merged with the default tags (with the extra tags taking precedent). Otherwise we lose many important aggregation tags that are usually set in the default config.

**Comment by jeremyist** [comment]
random thought, instead of the boolean `allow_extra_tags` what if I made it `extra_tags_key` that let you specify what key in the extras dict would be the tags. `None` would turn it off. Just in case someone wanted to use `tags` as a key for some other purpose... Or if the boolean is fine I'll leave it alone

**Review by madisonb — APPROVED** [review]
I agree with all of the above. code looks good.

**Pull request merged**
